In [8]:
import numpy as np

In [ ]:
#ARTHIMETIC OPERATION

In [2]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
a1+a2

array([ 6,  8, 10, 12])

In [3]:
a1-a2

array([-4, -4, -4, -4])

In [4]:
a1*a2

array([ 5, 12, 21, 32])

In [5]:
a1//a2

array([0, 0, 0, 0])

In [6]:
a1/a2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [7]:
a1**a2

array([    1,    64,  2187, 65536])

In [10]:
# BROADCASTING
# WHEN U WANT TO ADD SINGLE ELEMENT TO ALL ELEMENTS IN AN ARRAY MAKE USE OF BROADCASTING
# IT CAN BE PERFORMED IN VECTOR AS WELL AS MATRIX

# BROAAD CASITING IN VECTOR
arr=np.array([1,2,3,4])
arr+10

array([11, 12, 13, 14])

In [13]:
# BROAD CASTING IN MATRIX
arr2=np.arange(1,21).reshape(5,4)
arr2+10

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

In [15]:
arr2*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40]])

In [16]:
# DEEP AND SHALLOW COPY

In [17]:
# SHALLOW COPY CHANGES ARE NOT AFFECTED
# DEEP COPY CHANGES ARE AFFECTED

In [18]:
# SHALLOW COPY 
# IF WE DO SLICE AND AMAKE CHANGES IN IT WONT AFFECT ORGINAL ARRAY

In [20]:
arr3=np.arange(1,21)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
slice3=arr3[3:7]
slice3*10
# arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
# IN DEEEP COPY IF U COPY SLICE INTO ANOTHER VARIABLE THEN IT WILL AFFECT ORIGINAL ARRAY TOO

In [27]:
arr4=np.arange(1,21)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
slice4=arr4[3:7]
slice4

array([4, 5, 6, 7])

In [31]:
slicecopy=slice4
slicecopy[0]=99

In [32]:
slice4

array([99,  5,  6,  7])

In [33]:
#  TO AVOID DEEP COPY U CAN USE .copy() TO MAK DEEP COPY INTO SHALLOW COPY

In [34]:
# MATRIX OPERATIONS

In [35]:
# MATRIX MULTIPLICATION


In [37]:
A=np.array([
    [1,2],
    [3,4]
])

In [38]:
B=np.array([
    [5,6],
    [7,8]
])

In [39]:
A@B

array([[19, 22],
       [43, 50]])

In [40]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [41]:
# TRANSPOSE
A.T

array([[1, 3],
       [2, 4]])

In [42]:
# ADVANCE OPERATIONS

In [43]:
# STACKING OF ARRAYS(HOW TO JOIN TWO ARRAYS)
# CONSISTS OF VERTICAL AND HORIZONTAL STACK
# IN STACKING US USE ONLY VECTORS AND NOT MATRIX

In [45]:
# VERTICAL STACK(vertical that is columsn jodo dono array ka)
C=np.array([1,2,3,4])
D=np.array([5,6,7,8])
np.vstack((C,D))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
# HORIZONTAL STACK(horizontal that is rows jodo dono array ka)
np.hstack((C,D))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
# CoLUMN STACK INT THIS ARRANGE EACH ARRAY INTO VERTICAL MEANS VERTICAL ROTATE KARO VECTOR KO
np.column_stack((C,D))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [48]:
# SPLITTING ARRAY
# MEANS SPLITTING ARRAY INTO TWO PARTS EITHER HORIZONTAL OR VERTICAL AND SPLIT NUMBER MUST BE DIVISIBLE BY TOTAL ELEMENTS OF OROGINAL ARRAYA

In [49]:
arr5=np.arange(0,16).reshape(4,4)
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
np.vsplit(arr5,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [52]:
np.hsplit(arr5,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]