In [2]:
import numpy as np;

In [4]:
arr1=np.arange(11,21)
arr1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
#STARTING INDEX IS 1 AND ENDING INDEX IS 5 AS  IS EXCLUDING
arr1[1:6]

array([12, 13, 14, 15, 16])

In [6]:
arr1[:5]

array([11, 12, 13, 14, 15])

In [7]:
# SLICING WITH INCREMENTS HERE WE INCREMENT ELEMENTS WITH TWO
arr1[3::2]

array([14, 16, 18, 20])

In [10]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [12]:
arr[0,1]

np.int64(2)

In [15]:
# SLICING A SPECIFIC DIMENSIONAL FROM MATRIX 
# MEANS ROW 0 AND 1 PAKDO AND THEN COLUMN 1 AND 2 PAKDO
slice=arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [16]:
slice1=arr[3:6,3:5]
slice1

array([[19, 20],
       [24, 25],
       [29, 30]])

In [17]:
# VECTOR IS JUST 1 D ARAY THEY CAN BE COLUMN OR ROW

In [19]:
# SHOW ALL EVEN ELEMENTS FROM ARRAY JDR JDR EVEN HAE USE TRUE BOLNGE AND JDR JDR ODD USSE FALSE BOLENGE
bool_index=arr%2 == 0
bool_index

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [20]:
arr=arr[bool_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])