In [ ]:
# NUMPY ARRAY HAS SAME DATAYPES DATSTRUCUTRES
# FAST AND HIGH MEMORY EASY AND FAST IN VECTOR OPERATIONS



In [4]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [6]:
a=[1,2,3,"sid"]
a

[1, 2, 3, 'sid']

In [9]:
# IN NUMPY ARRAY ALL MUST HAVE SAME DATATYPES AND IF NOT THERE THEN IT WILL CONVERT IT INTO DEFAULT STRING DATATYPE
np.array(a)

array(['1', '2', '3', 'sid'], dtype='<U21')

In [10]:
# LIST DOESNT SUPPORTS MULTIDIMENIONAL BT WITH THE HELP OF NUMPY WE CAN CONVERT IT INTO MULTIDIM ARRAYa
l=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
l

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [11]:
np.array(l)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# ARRAY GENERATION FUNCTION

In [12]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [14]:
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
arr=np.ones((4,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
# Mujhe starting number se ending number tak SAME GAP wale fixed count numbers de do
arr=np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [13]:
# RANDOM GENERATION FUNCTION

In [5]:
# USED FOR NORMALIXATION VALUES BETWEEN 0-1
np.random.rand(10)

array([0.75321497, 0.89459386, 0.93446764, 0.97445411, 0.34921845,
       0.95293679, 0.19420291, 0.80583605, 0.80088191, 0.40644596])

In [8]:
# USED FOR STANDARIZATION VALUES BETWEEN 3 TO -3
np.random.randn(10)

array([-0.35232338, -0.68838937, -0.32568491, -0.2521342 ,  0.55391676,
       -0.18690209,  0.08386857, -0.92434537, -0.87127591,  0.18902796])

In [9]:
# GENERATE RANDOM NUMBERS BETWEEN RANGE 10-20 THAT TOO 10 RANDOM NMBERS
np.random.randint(10,20,10)

array([17, 10, 10, 16, 13, 13, 14, 18, 12, 13], dtype=int32)

In [14]:
# ARRAY ATTRIBUTES

In [24]:
# ATTRIBUTES KO CALL NHI KIYA JATA NOT LIKE FUNCTION
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr.shape

(3, 3)

In [18]:
arr.size

9

In [19]:
arr.dtype

dtype('int64')

In [20]:
# ARRAY METHODS

In [25]:
arr.min()

np.int64(1)

In [26]:
arr.max()

np.int64(9)

In [31]:
arr.sum()

np.int64(45)

In [33]:
arr.mean()

np.float64(5.0)

In [34]:
arr.std()

np.float64(2.581988897471611)

In [36]:
# DEFINES INDEX OF MAXIMUM EEENT IN AN 2D ARRAY
arr.argmax()

np.int64(8)

In [37]:
arr.argmin()

np.int64(0)

In [28]:
# SUM IS USED TO ADD ALL ELEMENTS IN ARRAY
# BY MENTIONING AXIS WE CAN SAY WHETHER WEE NEED TO SELECT ROW OR COLUMN ROW=1 COLUMN=0

In [29]:
np.sum(arr,0)

array([12, 15, 18])

In [30]:
np.sum(arr,1)

array([ 6, 15, 24])

In [38]:
arr1=np.arange(10)
arr1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# RESHAPE OF ARRAY MEANS NO OF ELEMENTS=NO OF ROWS * NO OF COLUMNS
# STORING RESHAPE ARRAY IS NOTHING BUT RESIZING
arr1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])