In [88]:
import numpy as np;

**Valid Sudoku**

In [89]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

s


array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [90]:
# TO BE VALID SUOKU SUM OF ALL ELEMENTS IN COLUMN AND AS WELL AS ROW MUST BE 45 AND AS WELL AS 3X3 MATRIX MUST BE 45

# ROWS
b=np.sum(s,axis=1)
for i in b:
    if i!=45:
        print("SUDOKU IS NOT VALID")
        break
else:
    print("SUDOKU IS VALID")

SUDOKU IS VALID


In [91]:
# Columns
c=np.sum(s,axis=0)
for i in c:
    if i!=45:
        print("SUDOKU IS NOT VALID")
        break
else:
    print("SUDOKU IS VALID")

SUDOKU IS VALID


In [92]:
# 3X3 MATRIX SUM
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3 ,j:j+3]
        m=np.sum(n)
        if m!=45:
            print("SUDOKU NOT VALID");
            break;
else:
    print("Sudoku valid");

Sudoku valid


**General Questions**

In [93]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [94]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [95]:
#Find the average age of students.
l=data[0: , :1]
l.mean()


np.float64(18.4)

In [96]:
#Extract Math marks of all students.
o=data[0:,1:2]
o

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [97]:
#Find the highest Science mark.
data.max()


np.int64(95)

In [98]:
#Get details of the student who scored more than 90 in Math.
# If we use this o=data[0:,1:2] we get 2d array and boolena works on 1d array that is vector
#  : ALL ROWS AND 1 MEANS THAT INDEX PARTICULAR COLUMN
bool_index = data[:,1] > 90
data[bool_index]

array([[19, 92, 88]])

In [99]:
#Increase Math marks of all students by 5.
# USE BROADCASTING
data[:,1]+=5
data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [100]:
#Find how many students are younger than 19.
len(data[data[:,0] < 19])

3

In [101]:
#Calculate the average marks in each subject (column-wise mean).
# WANT AVERAGE OF EACH COLUMN 
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [102]:
#Get data of students who scored at least 80 in both subjects.
# USED AND OPERATOR FOR TWO CONDITIONS
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [103]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0

data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])